import Nav from "@/components/nav/nav";
import "./globals.css";
import RQProviders from "@/server/RQprovider";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <RQProviders>
          <Nav />
          {children}
          <ReactQueryDevtools initialIsOpen={false} />
        </RQProviders>
      </body>
    </html>
  );
}
